### ISSUE TITLE
Add event_type field to events table

### ISSUE THREAD

**Issue by kevin-btc** [polyfire-ai/polyfire-api#88]
## Context
To improve data management and filterability, we need to introduce event types in the `events` table. This will enable us to filter events more efficiently.

## Requirement
We want to add a new `event_type` field to the `events` table, which will allow events to be categorized into different types. Here are some examples of event types we could introduce:
- request
- prompt
- data
etc...

## Tasks
- [ ] Add the `event_type` field to the `events` table, ensuring that it can accommodate different event categories.

**Comment by lowczarc** [comment]
This PR implements it: https://github.com/polyfire-ai/polyfire-api/pull/91
