### ISSUE TITLE
Problem with `|` characters in KV keys

### ISSUE THREAD

**Issue by kevin-btc** [polyfire-ai/polyfire-api#92]
## Problem description
When using the polyfire-js SDK version 0.2.5, i identified a bug concerning the management of KV (Key-Value) keys. When a key contains the `|` character, the key is either partially received, or not received at all. This problem occurs consistently and seems to be related specifically to the presence of the `|` character in the key.

## Context
- **SDK version:** polyfire-js 0.2.5
- **Usage:** KV key manipulation via SDK

## Impact
- Problem displaying keys containing the `|` character.
- At times the kv is not stored correctly in the database.

## Reproducing the problem
The problem can be reproduced by trying to manipulate a KV key containing the `|` character using the polyfire-js SDK. 

## Proposed solution
One possible solution would be to prohibit the use of the `|` character in KV keys when using the polyfire-js SDK. This could be achieved by adding key validation before sending keys for processing, and returning an error if an invalid key is detected.

**Comment by lowczarc** [comment]
After talking in private with @kevin-btc we couldn't manage to reproduce it. I'll close it for now.
